services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8001:8000"
  web:
    build:
      context: web
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: http://localhost:8001
    ports:
      - "3001:3000"
    depends_on:
      - api
